
#--------------------------------------------------------------
#You're approving a specific run of that workflow
#That run will execute the deployment steps defined in the YAML.
#In this case, deploying your azure-network3.2.bicep file to Azure
#----------------------------------------------------------------

#Adds approval gates for production deployments
name: Production Deployment with Approval

on:
  #workflow_dispatch:    # Manual trigger from GitHub Actions UI (run workflow button)
  
  #I skipped workflow_dispatch because i want this to be automatic and ask any user to review the deployment
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: Production
      #url: https://yourapp.com
      

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy with Approval
        run: |
          az deployment group create \
            --resource-group NetRG2 \
            --name azure-network3.2-${{ github.run_id }} \
            --template-file azure-network3.2.bicep \
            --parameters adminUsername='azureuser' adminPassword='${{ secrets.ADMIN_PASSWORD }}' \
            --query "properties.outputs"
